name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  workflow_dispatch:
  
  repository_dispatch:
    types: [run-test-ci]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build and publich
        run: |
          mvn install
          mvn install
          mvn install
          mvn install
          mvn install
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
          PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          EXTERNAL_REPOSITORY: ${{ github.event.client_payload.repository }}
          EXTERNAL_REPOSITORY_SHA: ${{ github.event.client_payload.sha }}
